### ISSUE TITLE
The user name is not updating

### ISSUE THREAD

**Issue by Aniruddha120** [chienhsiang-hung/kaggle-profile-summary-card#14]
Hey hi!
I hope you are doing well. Thanks for making the kaggle stats card! I am really happy. I just wanted to use the svd all round, but the name is not updating as my profile name. The name is still your's " Chien-Hsiang' 
Please look at the ss. 

Thanks! 
![image](https://github.com/chienhsiang-hung/kaggle-profile-summary-card/assets/34673269/262a5490-651a-42e4-baa6-aa34efb1ccf9)

**Comment by chienhsiang-hung** [comment]
Hi @Aniruddha120, thank you for bringing this up. It was a mistake of the test hard-coded var that didn't get updated in production env. It has been addressed. Should you have any other problems just let me know!
